apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    tier: backend
    app: nginx
spec:
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 80
      nodePort: 30678
  selector:
    tier: backend
    app: nginx
  type: LoadBalancer
